### ISSUE TITLE
Functions 'not defined' following Laravel Mix / Webpack introduction

### ISSUE THREAD

**Issue by jacksos101** [samuelgrant/fight-for-kidz#216]
**Describe the bug**
Application form functions such as 'showExperience()' are coming up as 'not defined' after running `npm run production` or `npm run dev`.

**Steps to Reproduce**
Ticking yes or no on the application form question 'Do you have any criminal convictions' for example, does not show or hide the text box for more information.

**Expected behaviour**
Functions should be found.

**Additional context**

**Comment by samuelgrant** [comment]
We've resolved this by not minifying certain functions.
