### ISSUE TITLE
URGENT medical tab 1 in applicant details modal not displaying correct data on prod

### ISSUE THREAD

**Issue by MitchellQ** [samuelgrant/fight-for-kidz#224]
**Describe the bug**
On the medical tab one on the production site is displaying yes on every question and is not displaying the correct information

see the client provide screenshot
![A4756019381A4CD88D86D66F76E0BF2F](https://user-images.githubusercontent.com/40969453/54111552-0218ec80-4449-11e9-9539-480c46091cc6.png)

**Steps to Reproduce**
I haven't been able to reproduce one my localhost

**Expected behaviour**
should display applicants details correctly

**Additional context**

**Comment by MitchellQ** [comment]
We have made a pr to master that we hope will resolve, waiting on client confirmation

**Comment by samuelgrant** [comment]
I've checked with my administrator account. This appears to be correct now.

**Comment by MitchellQ** [comment]
We have confirmation from the client that this is no longer an issue
