### ISSUE TITLE
Datepicker not working on IE

### ISSUE THREAD

**Issue by jacksos101** [samuelgrant/fight-for-kidz#234]
**Describe the bug**
Date picker does not render on IE, leaving applicants to enter their DOB as text. 

Front end and back end validation both allow dates through, even if the database isn't happy with it. Validation not validating to the correct standards.

The database has a fit and throws an exception as the format most people use isn't suitable for it.

**Steps to Reproduce**
Apply to fight in IE. Enter 01/01/1995 or equiv into DOB field.

**Expected behaviour**
Need to add a mask or some kind of code to check date format and convert into a format that the database likes.

OR stop people applying using IE.

**Additional context**

**Comment by jacksos101** [comment]
Adding placeholder to input probably best option (yyyy-mm-dd). If people follow the input then it will work. If they don't, however, site with throw a server error....

Only shows up on IE, other browsers that render the date picker simply ignore it, seemingly.

**Comment by samuelgrant** [comment]
Internet Explorer is no longer relevant, and MS Edge now uses Chromium.
